import {
  UserPlus,
  HeartPulse,
  Stethoscope,
  FlaskConical,
  Pill,
} from 'lucide-react';

export const ROLES = {
  receptionist: {
    key: 'receptionist',
    name: 'Receptionist',
    icon: UserPlus,
    color: 'blue',
    description: 'Register patients, manage payments and track patient flow.',
    email: 'receptionist@hospital.com',
    staffId: 'REC-001',
    fullName: 'Mary Wanjiru',
    dashboard: '/dashboard/receptionist',
    login: '/login/receptionist',
  },
  triage: {
    key: 'triage',
    name: 'Triage Nurse',
    icon: HeartPulse,
    color: 'green',
    description: 'Record patient vitals and assign triage priority.',
    email: 'triage@hospital.com',
    staffId: 'TRN-001',
    fullName: 'John Kamau',
    dashboard: '/dashboard/triage',
    login: '/login/triage',
  },
  clinician: {
    key: 'clinician',
    name: 'Clinician',
    icon: Stethoscope,
    color: 'purple',
    description: 'Conduct consultations, request labs and prescribe medication.',
    email: 'clinician@hospital.com',
    staffId: 'CLN-001',
    fullName: 'Dr. James Otieno',
    dashboard: '/dashboard/clinician',
    login: '/login/clinician',
  },
  lab: {
    key: 'lab',
    name: 'Laboratory Technician',
    icon: FlaskConical,
    color: 'orange',
    description: 'Process lab requests and upload test results.',
    email: 'lab@hospital.com',
    staffId: 'LAB-001',
    fullName: 'Grace Muthoni',
    dashboard: '/dashboard/lab',
    login: '/login/lab',
  },
  pharmacy: {
    key: 'pharmacy',
    name: 'Pharmacist',
    icon: Pill,
    color: 'teal',
    description: 'Dispense prescriptions and manage medication inventory.',
    email: 'pharmacist@hospital.com',
    staffId: 'PHM-001',
    fullName: 'Peter Njoroge',
    dashboard: '/dashboard/pharmacy',
    login: '/login/pharmacy',
  },
};

export const ROLE_LIST = Object.values(ROLES);
